### ISSUE TITLE
API - Multiple authentication backends

### ISSUE THREAD

**Issue by aviau** [surveil/surveil-meta#10]

**Comment by ddurieux** [comment]
Can you put the commit/pr related to this issue?

**Comment by aviau** [comment]
This was done a long time ago. See [here](https://github.com/stackforge/surveil/blob/master/etc/surveil/api_paste.ini). It is possible to select surveil-auth or something else.

For OpenStack, we use `authtoken`. At the moment `surveil-auth` is a dummy authentication. See [here](https://github.com/stackforge/surveil/blob/master/surveil/api/authmiddleware/auth.py#L93)
