### ISSUE TITLE
Packaging (rpm) - pack openstack-nova

### ISSUE THREAD

**Issue by vfournier11** [surveil/surveil-meta#72]
- Rename pack from linux to openstack

**Comment by ntfournier** [comment]
https://github.com/savoirfairelinux/monitoring-tools/pull/58

**Comment by ntfournier** [comment]
Can you review this please : https://github.com/savoirfairelinux/monitoring-tools/pull/59

**Comment by vfournier11** [comment]
https://github.com/savoirfairelinux/monitoring-tools/pull/60
